### PR TITLE
Various enhancements in Sitemap processor

### PR DESCRIPTION
**Pull request by ikalnytskyi**
(see commits for details)

### CODE REVIEW

**Comment by ikalnytskyi** [comment]
@PropheticBird That's a good question indeed! I remember discussing it with @malor, and the thing is a webserver usually compress things on-fly, i.e. when you request `sitemap.xml` - a webserver compress it and return, if you request it one more time - a webserver compress it once again. So why to do the job multiple times? It's easier to compress just once, and then share it because, according to the sitemap standard, it's allowed to be gzipped and hence any client should be able to decompress it if needed.

**Comment by PropheticBird** [comment]
@ikalnytskyi OK, I see your point, although in my opinion compressing multiple times is a flow in a webserver's implementation rather than a missing sitemap processor requirement. I mean there are caches and other techniques on the webserver side, which should effectively work around the issue.. 
Anyway, even if compression is enabled for sitemap processor output, should other documents be compressed as well? Perhaps, it can even be implemented as a separate processor?  What do you think about it?

**Comment by ikalnytskyi** [comment]
> even if compression is enabled for sitemap processor output, should other documents be compressed as well?

No, they should not. On a webserver level, we have the following flow:

* An HTTP client says it's ok to use compression by passing `Accept-Encoding: gzip, deflate` header.
* An HTTP server responds using compression (if supported), and claims that compression is used by passing `Content-Encoding: gzip` header.
* An HTTP client checks `Content-Encoding`, and if specified it's used to decompress the response.

So basically, if you request a file, it's compression and decompression is done automatically by HTTP, so in the end you always end up with decompressed entity.

In case of `sitemap.xml.gz`, we are requesting compressed file, and we will receive compressed file. HTTP will not decompress it for us. The job for decompressing should be performed by consumer, the one who requested the file. And it's ok, since according to the Sitemap protocol the sitemap may be compressed using gzip and any consumer should be ready for this. If we are talking about HTMLs, they should not be compressed and browsers do not expect them to be compressed. Any compression/decompression to HTMLs, again, is done by HTTP protocol.

**Comment by ikalnytskyi** [comment]
Another thing is having sitemap gzipped on filesystem might help to save space. For instance, I generated a sitemap with unique entries. It contains 50000 URLs (which is according to the protocol is upper bound).

```bash
$ du -h sitemap*
29M	sitemap.xml
960K	sitemap.xml.gz
```

As you can see, gzipped version almost 30 times thinner in size.

**Comment by PropheticBird** [comment]
Thanks for detailed explanation of how compression works on a webserver level! I understand now that it is needed only for `sitemap.xml` as the client should be ready to receive the compressed version of the file. Merging.

**Pull request merged**
